### ISSUE TITLE
Avoid out-of-tree ramoops setup patch

### ISSUE THREAD

**Issue by lambdadroid** [me176c-dev/linux-me176c#2]
Right now, `ME176C: x86/platform: Register ramoops device and reserve memory` is used to reserve memory for the ramoops memory region and to register it.

It could be also set up using the kernel command line, but having to type this for every Linux installation would be rather annoying. Maybe it could be set up in the bootloader?

**Comment by stephan-gh** [comment]
I decided to get rid of the patch entirely for now. It's not working very well....
