### ISSUE TITLE
PostmarketOS flash rootFS error.

### ISSUE THREAD

**Issue by ReubenBTalbott** [me176c-dev/linux-me176c#5]
I have followed the pmOS guide https://wiki.postmarketos.org/wiki/ASUS_MeMO_Pad_7_(asus-me176c) to get linux on my MeMo pad 7. The ESP flashes fine and I can access it and boot stock android and TWRP (which I installed) from it. But when I go to install the RootFS I get this error 
`reuben@fatso ~ % fastboot flash data asus-me176c.img`
`Invalid sparse file format at header magic`
`Sending sparse 'data' 1/2 (513219 KB)              OKAY [ 12.676s]`
`Writing 'data'                                     FAILED (remote: 'flash_cmds error!')`
`fastboot: error: Command failed`
`reuben@fatso ~ %`

I'm sorry if this is the wrong place to post this but I could not find a pmOS repo and don't know where else to post this.

Any help is appreciated! 
Reuben

**Comment by stephan-gh** [comment]
postmarketOS issues are at https://gitlab.com/postmarketOS/pmaports/issues

At the moment, the postmarketOS port for me176c is maintained by @Mis012. I haven't really had the time to try it out myself, yet.
